import { size } from "zod";
import { Produit } from "./types";

export const produits = [
  { 
    id: 1,
  name: "Montre",
  price: 10000,
  image: "/telechargement2.jpeg",
  description: "Couleur rose, très bonne qualité",
  quantité: 10,
  category: "bijoux",
 colors: ["gold"]
  },
  { 
    id: 2,
    name: "Van Cleef ",
    price: 2000, 
    image: "/telechargement1.jpeg",
    description:"Plaqué or",
    quantité: 20,
    category :"bijoux",
    colors: ["white","red","purple","blue","black","gold","green"]
  },
  { 
    id: 3,
    name: "Bracelet Cartier", 
    price: 3000, 
    image: "/telechargement3.jpeg",
    description: "couleur doré",
    quantité:8,
    category: "bijoux",
     colors: ["#ffcf57b4"]
  },
   { 
    id: 4,
    name: "zara Parfum", 
    price: 7000, 
    image: "/tel.jpeg",
    description: "parfum de 100ml ",
    quantité:10,
    category: "parfumerie",
      subCategory: "femme",

  },
  { 
    id: 5,
    name: "L'HOMME IDEAL", 
    price: 130000, 
    image: "/tel2.jpeg",
    description: "Eau de parfum de marque GUERLAIN ,parfum de 100ml ",
    quantité:12,
    category: "parfumerie",
      subCategory: "homme",
  },
   { 
    id: 6,
    name: "BLEU de CHANNEL", 
    price: 90000, 
    image: "/tel3.jpeg",
    description: "Eau de parfum de marque CHANNEL ,parfum de 100ml ",
    quantité:10,
    category: "parfumerie",
      subCategory: "homme",
  },
 { 
    id: 7,
    name: "L'HOMME YSL", 
    price:  80000, 
    image: "/tel4.jpeg",
    description: "eau de parfum YVES SAINT LAURENT L'HOMME LE PARFUM 100ml",
    quantité:9,
    category: "parfumerie",
      subCategory: "homme",
  },
 { 
    id: 8,
    name: "BOSS hugo boss", 
    price:  100000, 
    image: "/tel5.jpeg",
    description: "eau de parfum Hugo Boss BOSS Bottled ,LE PARFUM 100ml",
    quantité:5,
    category: "parfumerie",
      subCategory: "homme",
  }, 
  { 
    id: 9,
    name: "SAUVAGE DIOR", 
    price:  90000, 
    image: "/tel6.jpeg",
    description: "eau de parfum DIOR ,LE PARFUM 100ml",
    quantité:10,
    category: "parfumerie",
      subCategory: "homme",
  }, 
    { 
    id: 10,
    name: "JEAN PAUL GAULTIER", 
    price:  80000, 
    image: "/tel7.jpeg",
    description: "eau de parfum JEAN PAUL GAULTIER,LE PARFUM 100ml",
    quantité:10,
    category: "parfumerie",
      subCategory: "homme",
  }, 
   { 
    id: 11,
    name: "Chaussure zara ", 
    price:  20000, 
    image: "/chauss1.jpg",
    description: "pointure 37 à 41",
    quantité:10,
    category: "mode",
     subCategory: "chaussures",
     colors: ["pink","red","black","gold"],
     size: ["39", "40", "41"]
  }, 
   { 
    id: 12,
    name: "zara transparant", 
    price:  20000, 
    image: "/chauss2.jpg",
    description: " pointure 37 à 41",
    quantité:10,
    category: "mode",
     subCategory: "chaussures",
  }, 
   { 
    id: 13,
    name: "zara orange", 
    price:  20000, 
    image: "/chauss3.jpg",
    description: "pointure 37 à 41",
    quantité:10,
    category: "mode",
     subCategory: "chaussures",
  }, 
   { 
    id: 14,
    name: "Padam ", 
    price:  10000, 
    image: "/padam.jpg",
    description: "pointure 37 à 41.",
    quantité:10,
    category: "mode",
    colors: ["white","red","purple","blue","black","gold","green"]
  }, 
     { 
    id: 15,
    name: "bougie parfumés", 
    price:  10000, 
    image: "/bougie1.jpg",
    description: "coconut de marque mahogany coconut",
    quantité:10,
    category: "parfumerie",
      subCategory: "bougies",

  },
     { 
    id: 16,
    name: "Bougie parfumée", 
    price:  10000, 
    image: "/bougie2.jpg",
    description: " couleur beige de marque APPLE CRISP",
    quantité:10,
    category: "parfumerie",
    colors: ["pink","beige"],
      subCategory: "bougies",
  },
   { 
    id: 17,
    name: "sac lacoste ", 
    price:  10000, 
    image: "/sac1.jpg",
    description: "",
    quantité:10,
    category: "mode",
    colors: ["pink","beige"],
     subCategory: "sacs",
  },
  { 
    id: 18,
    name: "sac jimmy choco ", 
    price:  30000, 
    image: "/sac2.jpg",
    description: "",
    quantité:10,
    category: "mode",
     subCategory: "sacs",
  },
  { 
    id: 19,
    name: "sac ysl ", 
    price:  30000, 
    image: "/sac3.jpg",
    description: "",
    quantité:10,
    category: "mode",
     subCategory: "sacs",
  },
  { 
    id: 20,
    name: "bioderma ", 
    price:  15000, 
    image: "/bioderma.jpg",
    description: "",
    quantité:10,
    category: "beaute"
  },
   { 
    id: 21,
    name: "cerave ", 
    price:  10500, 
    image: "/cerave.jpg",
    description: "",
    quantité:10,
    category: "beaute"
  },
   { 
    id: 22,
    name: "crest ", 
    price:  8000, 
    image: "/crest.png",
    description: "",
    quantité:10,
    category: "beaute"
  },
   { 
    id: 23,
    name: "eos ", 
    price:  12000, 
    image: "/eos.jpg",
    description: "",
    quantité:10,
    category: "beaute"
  },
   { 
    id: 24,
    name: "listerine ", 
    price:  8000, 
    image: "/listerine.jpg",
    description: "",
    quantité:10,
    category: "beaute"
  },
  { 
    id: 25,
    name: "sac hermes ", 
    price:  15000, 
    image: "/sac4.jpg",
    description: "",
    quantité:10,
    category: "mode",
    subCategory: "Sacs",
  },
   
  { 
    id: 26,
    name: "ASTA'love", 
    price:  25000, 
    image: "/ens1.jpg",
    description: "une robe de la marque MADASY, en crepe ",
    quantité:10,
    category: "vetements",
   colors: ["#1e3eccff", "#690fa2ff"],
     subCategory: "ensemble",

  },
  { 
    id: 27,
    name: "MADY", 
    price:  25000, 
    image: "/ens2.jpg",
    description: "une robe de la marque SOMALUXURY, en soie",
    quantité:10,
    category: "vetements",
    subCategory: "ensemble",
  },
 { 
    id: 28,
    name: "KHEURY'DAROU", 
    price:  20000, 
    image: "/ens3.jpg",
    description: "Un ensemble de la marque SOMALUXURY, en soie",
    quantité:10,
    category: "vetements",
    taille:["XS","S","M","L","XL"],
     subCategory: "ensemble",
  },
   { 
    id: 29,
    name: "Robe", 
    price:  12000, 
    image: "/robe1.jpg",
    description: "",
    quantité:10,
    category: "vetements",
      subCategory: "robe",
  },
   { 
    id: 30,
    name: "Robe", 
    price:  17000, 
    image: "/robe2.jpg",
    description: "",
    quantité:10,
    category: "vetements",
      subCategory: "robe",
  },
   { 
    id: 31,
    name: "robe", 
    price:  15000, 
    image: "/robe3.jpg",
    description: "",
    quantité:10,
    category: "vetements",
      subCategory: "robe",
  },
   { 
    id: 32,
    name: "The ordinary  ", 
    price:  8000, 
    image: "/ord1.jpg",
    description: "",
    quantité:10,
    category: "beaute"
  },
   { 
    id:   33,
    name: "The ordinary ", 
    price:  10000, 
    image: "/ord2.jpg",
    description: "",
    quantité:10,
    category: "beaute"
  },
   { 
    id:   34,
    name: "bracelet", 
    price:  5000, 
    image: "/bracelet1.jpg",
    description: "",
    quantité:10,
    category: "bijoux"
  },
   { 
    id:   35,
    name: "bracelet", 
    price:  5000, 
    image: "/bracelet2.jpg",
    description: "",
    quantité:10,
    category: "bijoux"
  },
   { 
    id:   36,
    name: "bracelet", 
    price:  5000, 
    image: "/bracelet3.png",
    description: "",
    quantité:10,
    category: "bijoux"
  },
   { 
    id:   37,
    name: "bracelet", 
    price:  5000, 
    image: "/montre1.jpg",
    description: "",
    quantité:10,
    category: "bijoux"
  },
     { 
    id:   38,
    name: "Parfum ", 
    price:  80000, 
    image: "/femme1.jpg",
    description: "",
    quantité:10,
    category: "parfumerie",
      subCategory: "femme",
  },
 { 
    id:   39,
    name: "Parfum ", 
    price:  100000, 
    image: "/femme2.jpg",
    description: "",
    quantité:10,
    category: "parfumerie",
      subCategory: "femme",
  },
  {
  id: 40,
  name: "FAA'STAR",
  price: 25000,
  image: "/fabii.jpg",        // image principale (affichage par défaut)
  images: [                   // toutes les images du produit
    "/fabii.jpg",
    "/fabii2.jpg",
  ],
 
  description: "Une robe de la marque MADASY, en crêpe",
  quantité: 10,
  category: "vetements",
  colors: ["#a2710f24", "#0f0fa2ff",],
  subCategory: "ensemble",
  marque: "MADASY"
}


];
